# Root configuration with region definitions

[regions.main]
initial = "MainSpawnGold"
file = "regions/main.toml"

[regions.quasar]
file = "regions/quasar.toml"

[regions.storm]
file = "regions/storm.toml"

[regions.monitor]
initial = "MonitorWarmup"
file = "regions/monitor.toml"
background = true

[regions.placeholder]
file = "regions/tower.toml"

[states.Root]